import type { PasskeyPromptContext } from "../runtime/messages";

export function renderPasskeyPrompt(context: PasskeyPromptContext, accept: (itemId?: string) => Promise<void>, dismiss: () => Promise<void>, rootDocument: Document = document): void {
  rootDocument.getElementById("monica-passkey-prompt-host")?.remove();
  const host = rootDocument.createElement("div"); host.id = "monica-passkey-prompt-host"; host.style.cssText = "all:initial;position:fixed;inset:0;z-index:2147483647;pointer-events:none";
  const shadow = host.attachShadow({ mode: "open" });
  shadow.innerHTML = `<style>*{box-sizing:border-box}.card{pointer-events:auto;position:fixed;top:18px;right:18px;width:min(390px,calc(100vw - 36px));padding:18px;border-radius:28px;background:#fff8ff;color:#242126;box-shadow:0 18px 54px #1f182866;font:14px system-ui;display:grid;gap:14px}.head{display:flex;gap:12px;align-items:center}.icon{width:44px;height:44px;border-radius:16px;display:grid;place-items:center;background:#eaddff;font-size:22px}.copy{display:grid;gap:3px}.muted{color:#655d68;font-size:12px}button{min-height:44px;border:0;border-radius:22px;padding:0 16px;font:inherit;font-weight:700;cursor:pointer}.choices{display:grid;gap:8px}.choice{width:100%;text-align:left;background:#f4ecf5}.actions{display:flex;justify-content:flex-end;gap:8px}.cancel{background:transparent;color:#6750a4}.primary{background:#6750a4;color:white}</style>`;
  const card = rootDocument.createElement("section"); card.className = "card"; card.setAttribute("role", "dialog");
  card.innerHTML = `<div class="head"><span class="icon">🔑</span><div class="copy"><strong>${context.operation === "create" ? "创建 Monica Passkey？" : "使用 Monica Passkey？"}</strong><span class="muted"></span></div></div>`;
  (card.querySelector(".muted") as HTMLElement).textContent = `${context.rpName || context.rpId} · ${context.userName || context.rpId}${context.operation === "create" && context.saveTargetName ? ` · 保存至 ${context.saveTargetName}` : ""}`;
  let selected = context.credentials[0]?.itemId;
  if (context.operation === "get") { const choices = rootDocument.createElement("div"); choices.className = "choices"; for (const credential of context.credentials) { const button = rootDocument.createElement("button"); button.className = "choice"; button.textContent = `${credential.title} · ${credential.userName || "无用户名"} · ${credential.sourceMode === "bitwarden" ? "Bitwarden" : "浏览器本地"}`; button.onclick = () => { selected = credential.itemId; for (const item of Array.from(choices.children)) (item as HTMLElement).style.outline = ""; button.style.outline = "2px solid #6750a4"; }; choices.append(button); } card.append(choices); }
  const actions = rootDocument.createElement("div"); actions.className = "actions"; const cancel = rootDocument.createElement("button"); cancel.className = "cancel"; cancel.textContent = "取消"; const confirm = rootDocument.createElement("button"); confirm.className = "primary"; confirm.textContent = context.operation === "create" ? "创建 Passkey" : "继续登录"; actions.append(cancel, confirm); card.append(actions); shadow.append(card); rootDocument.documentElement.append(host);
  cancel.onclick = () => void dismiss().finally(() => host.remove());
  confirm.onclick = () => { confirm.disabled = true; void accept(selected).then(() => host.remove()).catch((error) => { confirm.disabled = false; confirm.textContent = error instanceof Error ? error.message : "操作失败"; }); };
  rootDocument.defaultView?.setTimeout(() => host.remove(), Math.max(0, context.expiresAt - Date.now()) + 100);
}
