import { createApp } from "vue";
import "@m3e/web/checkbox";
import "@m3e/web/switch";
import "@m3e/web/radio-group";
import "@m3e/web/expansion-panel";
import "@m3e/web/dialog";
import "@m3e/web/segmented-button";
import "@m3e/web/tabs";
import "@m3e/web/list";
import App from "./App.vue";
import "./styles.css";
import "./manager.css";
import "./responsive.css";
import "./vault-layout.css";
import "./detail-layout.css";
import "./editor-layout.css";
import "./motion.css";
import "./material.css";
import "./nothing.css";
import "./material-manager.css";
import "./lib/menu-layout";
import { installMaterialControls } from "./lib/material-controls";
import { installMaterialDialogs } from "./lib/material-dialog";
import "./lib/action-button-layout";
import { initializeI18n } from "./i18n";

void initializeI18n().then(() => createApp(App).use(installMaterialControls).use(installMaterialDialogs).mount("#root"));
