name: Dependency Review

on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: Base Git ref or commit SHA to compare
        required: true
      head_ref:
        description: Head Git ref or commit SHA to compare
        required: true
        default: main
  pull_request:

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          base-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.base_ref || github.event.pull_request.base.sha }}
          head-ref: ${{ github.event_name == 'workflow_dispatch' && inputs.head_ref || github.event.pull_request.head.sha }}
          fail-on-severity: moderate
          deny-licenses: GPL-2.0, LGPL-2.0
